name: Mark stale issues and pull requests
on:
  schedule:
    - cron:  '26 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:
    if: github.repository != 'NujSuper/docker-openssh-server'
    permissions:
      issues: write
      pull-requests: write
    uses: linuxserver/github-workflows/.github/workflows/issues-cron.yml@v1
    secrets: inherit
